---
- name: Déployer l'application Angular sur le serveur
  hosts: myservers
  become: true
  tasks:

    # Mettre à jour les paquets
    - name: Mettre à jour les paquets APT
      apt:
        update_cache: yes

    # Installer Nginx
    - name: Installer Nginx
      apt:
        name: nginx
        state: present

    - name: Démarrer et activer le service Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    # Installer Git et curl
    - name: Installer Git et curl
      apt:
        name:
          - git
          - curl
        state: present

    # Cloner le dépôt Angular officiel (fourni par OpenClassrooms)
    - name: Cloner le dépôt Angular
      git:
        repo: "https://github.com/OpenClassrooms-Student-Center/G-rez-l-int-gration-continue-avec-Git-et-scripts-Application-Angular.git"
        dest: /var/www/angular-app
        version: main

    # Installer Node.js depuis NodeSource (corrige les erreurs apt 400)
    - name: Ajouter le dépôt NodeSource pour Node.js 18
      shell: curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      args:
        executable: /bin/bash

    - name: Installer Node.js
      apt:
        name: nodejs
        state: present
        update_cache: yes

    - name: Vérifier la version de Node.js
      command: node -v
      register: node_version

    - debug:
        msg: "Version de Node.js installée : {{ node_version.stdout }}"

    # Installer les dépendances npm et construire l'app Angular
    - name: Installer les dépendances npm
      command: npm install
      args:
        chdir: /var/www/angular-app

    - name: Générer la build Angular
      command: npm run build --prod
      args:
        chdir: /var/www/angular-app

    # Déployer la build Angular sur Nginx
    - name: Supprimer l'ancien contenu du répertoire Nginx
      file:
        path: /var/www/html
        state: absent

    - name: Copier la build Angular vers le répertoire Nginx
      copy:
        src: /var/www/angular-app/dist/
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0755'
        remote_src: yes
      notify: Redémarrer Nginx

    # Configuration Nginx
    - name: Créer la configuration Nginx pour Angular
      copy:
        dest: /etc/nginx/sites-available/angular-app
        content: |
          server {
              listen 80;
              server_name _;
              root /var/www/html;
              index index.html;
              location / {
                  try_files $uri $uri/ /index.html;
              }
          }
      notify: Redémarrer Nginx

    - name: Activer la configuration Nginx
      file:
        src: /etc/nginx/sites-available/angular-app
        dest: /etc/nginx/sites-enabled/angular-app
        state: link
      notify: Redémarrer Nginx

  handlers:
    - name: Redémarrer Nginx
      service:
        name: nginx
        state: restarted